project:
  type: website

website:
  title: "VAA_handson_exercise"
  navbar:
    left: 
      - icon: pencil-square
        text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Part 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Part 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual
