project:
  type: website

execute:
  freeze: false

website:
  title: "VAA_handson_exercise"
  navbar:
    left:
      - icon: pencil-square
        text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Part 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
          - text: "Hands-on Part 2"
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html
          - text: "Hands-on Part 3a"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html
          - text: "Hands-on Part 3b"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html
          - text: "Hands-on Part 4a"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html
          - text: "Hands-on Part 4b"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html
          - text: "Hands-on Part 4c"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html
          - text: "Hands-on Part 4d"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html
format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual